"""add_user_score

Revision ID: 06082a522c59
Revises: b892a0c39ba2
Create Date: 2025-12-10 21:59:46.200349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06082a522c59'
down_revision: Union[str, Sequence[str], None] = 'b892a0c39ba2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingredients_name'), table_name='ingredients')
    op.add_column('users', sa.Column('score', sa.Integer(), nullable=False, server_default='0'))
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_users_full_name'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_full_name'), 'users', ['full_name'], unique=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'score')
    op.create_index(op.f('ix_ingredients_name'), 'ingredients', ['name'], unique=False)
    # ### end Alembic commands ###
