"""add_profile_fruits_and_fat_goal

Revision ID: a77282d5393f
Revises: cc6e2913c313
Create Date: 2025-12-09 19:13:03.042695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a77282d5393f'
down_revision: Union[str, Sequence[str], None] = 'cc6e2913c313'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('eats_fruit', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('profiles', sa.Column('body_fat_goal', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'eats_fruit')
    op.drop_column('profiles', 'body_fat_goal')
    # ### end Alembic commands ###
