"""add_recipe_filters_and_ingredient_calories

Revision ID: cc6e2913c313
Revises: e39040fb4c29
Create Date: 2025-11-30 18:39:35.855564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc6e2913c313'
down_revision: Union[str, Sequence[str], None] = 'e39040fb4c29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredients', sa.Column('calories', sa.Float(), nullable=True))
    op.add_column('recipes', sa.Column('category', sa.String(), nullable=True))
    op.add_column('recipes', sa.Column('is_favorite', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'is_favorite')
    op.drop_column('recipes', 'category')
    op.drop_column('ingredients', 'calories')
    # ### end Alembic commands ###
