"""add_recipe_method

Revision ID: e39040fb4c29
Revises: 8181e96ae511
Create Date: 2025-11-30 01:05:17.542482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e39040fb4c29'
down_revision: Union[str, Sequence[str], None] = '8181e96ae511'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('preparation_method', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'preparation_method')
    # ### end Alembic commands ###
