"""add_diet_preferences

Revision ID: f3763d74415d
Revises: 9a7fdce8d4ed
Create Date: 2025-11-29 22:14:40.994087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3763d74415d'
down_revision: Union[str, Sequence[str], None] = '9a7fdce8d4ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('diet_type', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('allergies', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('food_likes', sa.Text(), nullable=True))
    op.add_column('profiles', sa.Column('food_dislikes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'food_dislikes')
    op.drop_column('profiles', 'food_likes')
    op.drop_column('profiles', 'allergies')
    op.drop_column('profiles', 'diet_type')
    # ### end Alembic commands ###
